### ISSUE TITLE
Connection to postgres fails from vscode dev container

### ISSUE THREAD

**Issue by ThorbenJensen** [codeformuenster/muenster-jetzt#155]
When setting up the backend dev environment (hopefully) as documented,
`python -m mj migrate` fails with:

>  peewee.OperationalError: could not connect to server: Connection refused
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?
could not connect to server: Cannot assign requested address
        Is the server running on host "localhost" (::1) and accepting
        TCP/IP connections on port 5432?

This error can be reproduced (on my machine) when running from Python inside the vscode container setup:
```
import psycopg2
conn = psycopg2.connect(database="muensterjetzt", user='dbuser', password='...', host='localhost', port= '5432')
```
However, establishing a connection to the database from outside the dev environment (i.e. a usual terminal) works.

Any ideas how I could make sure that the postgres service/container is accessible from within my backend dev container?
@jdemaeyer, did you have to solve this issue?

**Comment by jdemaeyer** [comment]
Mhh, I didn't encounter this as I don't use VSCode. @bCyberBasti?

**Comment by ThorbenJensen** [comment]
ah, that means that you are running the `mj` scripts from outside any container, @jdemaeyer?
in that case, I might indeed have to review our VSCode Remote Containers settings with @bCyberBasti.

**Comment by bCyberBasti** [comment]
had that, been there 😄 

my problem was that i didn't have the right `.env` file in the `backend` folder. if you've started the postgres container once without the configuration it "remembers" the initialisation and is in a wrong state.

steps to fix:
- delete the dev postgres container and its associated volume
- create the `.env` file based on `.env.example`
- start everything "as normal"
- it should now work™️

**Comment by jdemaeyer** [comment]
> ah, that means that you are running the `mj` scripts from outside any container, @jdemaeyer?

Yeah, I use the Python installation on my host machine with the mj-specific dependencies in a virtual environment

**Comment by ThorbenJensen** [comment]
thx for the hint, @bCyberBasti 
however, still having the same connection problem from within the Remote Container. :-(
we might have to have a debugging session at some point.

i'll next try @jdemaeyer's approach

**Comment by ubergesundheit** [comment]
@ThorbenJensen is this resolved?

**Comment by ubergesundheit** [comment]
@ThorbenJensen and @bCyberBasti will meet and close this after this is resolved
